//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace apiHelp
{
    using System;
    using System.Collections.Generic;
    
    public partial class CBOF_BASE_DATA
    {
        public string GUID { get; set; }
        public string NAME { get; set; }
        public string HEATID { get; set; }
        public string PREHEATID { get; set; }
        public string STEELGRADEINDEX { get; set; }
        public string STEELGRADE { get; set; }
        public string SHIFT { get; set; }
        public string TEAM { get; set; }
        public string HEADFURNACE { get; set; }
        public string ASSISTANT { get; set; }
        public string SECONDHAND { get; set; }
        public Nullable<System.DateTime> PRODUCTIONDATE { get; set; }
        public Nullable<System.DateTime> STATISTICSDATE { get; set; }
        public Nullable<short> LOCKED { get; set; }
        public Nullable<int> NC_CONFIRM_FLAG { get; set; }
        public string TS { get; set; }
        public string DR { get; set; }
    }
}
