//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace apiHelp
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<CBOF_BASE_DATA> CBOF_BASE_DATA { get; set; }
        public DbSet<S_RESOURCE_T> S_RESOURCE_T { get; set; }
        public DbSet<S_RESOURCEROLE_T> S_RESOURCEROLE_T { get; set; }
        public DbSet<S_ROLE_T> S_ROLE_T { get; set; }
        public DbSet<S_ROLEUSER_T> S_ROLEUSER_T { get; set; }
        public DbSet<S_USER_T> S_USER_T { get; set; }
    }
}
