//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace apiHelp
{
    using System;
    using System.Collections.Generic;
    
    public partial class S_RESOURCE_T
    {
        public S_RESOURCE_T()
        {
            this.S_RESOURCEROLE_T = new HashSet<S_RESOURCEROLE_T>();
        }
    
        public string GUID { get; set; }
        public string RESOURCEID { get; set; }
        public string RESOURCEICON { get; set; }
        public string RESOURCELINK { get; set; }
        public string RESOURCENAME { get; set; }
        public string RESOURCETYPE { get; set; }
        public string ISDISPLAY { get; set; }
        public string TS { get; set; }
        public string DR { get; set; }
        public string FGUID { get; set; }
        public string REMARK { get; set; }
    
        public virtual ICollection<S_RESOURCEROLE_T> S_RESOURCEROLE_T { get; set; }
    }
}
