//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace apiHelp
{
    using System;
    using System.Collections.Generic;
    
    public partial class S_RESOURCEROLE_T
    {
        public string GUID { get; set; }
        public string ROLEID { get; set; }
        public string RESOURCEID { get; set; }
        public string TS { get; set; }
        public string DR { get; set; }
        public string FGUID { get; set; }
        public string REMARK { get; set; }
    
        public virtual S_RESOURCE_T S_RESOURCE_T { get; set; }
    }
}
