//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace apiHelp
{
    using System;
    using System.Collections.Generic;
    
    public partial class S_USER_T
    {
        public S_USER_T()
        {
            this.S_ROLEUSER_T = new HashSet<S_ROLEUSER_T>();
        }
    
        public string GUID { get; set; }
        public string USERID { get; set; }
        public string DISPLAYNAME { get; set; }
        public string PASSWORD { get; set; }
        public Nullable<int> AGE { get; set; }
        public string EMAIL { get; set; }
        public string NATION { get; set; }
        public string PHONE { get; set; }
        public string SERVICING { get; set; }
        public string SEX { get; set; }
        public string USERIMAGE { get; set; }
        public string TS { get; set; }
        public string DR { get; set; }
        public string FGUID { get; set; }
        public string REMARK { get; set; }
    
        public virtual ICollection<S_ROLEUSER_T> S_ROLEUSER_T { get; set; }
    }
}
